[tox]
envlist = py311, flake8, black, ruff, bandit, pip-audit
skip_missing_interpreters = true

[testenv]
deps =
    .
    pytest>=7.0
commands = pytest {posargs}

[testenv:flake8]
deps = flake8
commands = flake8 src/ tests/

[testenv:black]
deps = black>=23.1.0
commands = black -S -t py311 -l 120 --check --diff src/ tests/

[testenv:black-format]
skip_install = true
deps = 
    black >= 23.1.0
commands = 
    black -S -t py311 -l 120 src/ tests/

[testenv:ruff]
deps = ruff>=0.4
commands = ruff check src/ tests/

[testenv:bandit]
deps = bandit
commands = bandit -r src/novabucks/ -ll

[testenv:pip-audit]
deps =
    .
    pip-audit
skip_install = true
commands_pre = python -m pip install --upgrade pip setuptools
commands = pip-audit --skip-editable

[flake8]
max-line-length = 120
exclude = .venv,build,dist,.tox,.eggs
extend-ignore = E203
